/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PathlessLayoutImport } from './routes/_pathlessLayout'
import { Route as PostsRouteImport } from './routes/posts.route'
import { Route as IndexImport } from './routes/index'
import { Route as RatingIndexImport } from './routes/rating/index'
import { Route as PostsIndexImport } from './routes/posts.index'
import { Route as NoticiasIndexImport } from './routes/noticias/index'
import { Route as ComunicadosIndexImport } from './routes/comunicados/index'
import { Route as PostsPostIdImport } from './routes/posts.$postId'
import { Route as NoticiasNoticiaSlugImport } from './routes/noticias/$noticiaSlug'
import { Route as ComunicadosComunicadoIdImport } from './routes/comunicados/$comunicadoId'
import { Route as PathlessLayoutNestedLayoutImport } from './routes/_pathlessLayout/_nested-layout'
import { Route as PathlessLayoutNestedLayoutRouteBImport } from './routes/_pathlessLayout/_nested-layout/route-b'
import { Route as PathlessLayoutNestedLayoutRouteAImport } from './routes/_pathlessLayout/_nested-layout/route-a'

// Create/Update Routes

const PathlessLayoutRoute = PathlessLayoutImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRoute,
} as any)

const PostsRouteRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RatingIndexRoute = RatingIndexImport.update({
  id: '/rating/',
  path: '/rating/',
  getParentRoute: () => rootRoute,
} as any)

const PostsIndexRoute = PostsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PostsRouteRoute,
} as any)

const NoticiasIndexRoute = NoticiasIndexImport.update({
  id: '/noticias/',
  path: '/noticias/',
  getParentRoute: () => rootRoute,
} as any)

const ComunicadosIndexRoute = ComunicadosIndexImport.update({
  id: '/comunicados/',
  path: '/comunicados/',
  getParentRoute: () => rootRoute,
} as any)

const PostsPostIdRoute = PostsPostIdImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => PostsRouteRoute,
} as any)

const NoticiasNoticiaSlugRoute = NoticiasNoticiaSlugImport.update({
  id: '/noticias/$noticiaSlug',
  path: '/noticias/$noticiaSlug',
  getParentRoute: () => rootRoute,
} as any)

const ComunicadosComunicadoIdRoute = ComunicadosComunicadoIdImport.update({
  id: '/comunicados/$comunicadoId',
  path: '/comunicados/$comunicadoId',
  getParentRoute: () => rootRoute,
} as any)

const PathlessLayoutNestedLayoutRoute = PathlessLayoutNestedLayoutImport.update(
  {
    id: '/_nested-layout',
    getParentRoute: () => PathlessLayoutRoute,
  } as any,
)

const PathlessLayoutNestedLayoutRouteBRoute =
  PathlessLayoutNestedLayoutRouteBImport.update({
    id: '/route-b',
    path: '/route-b',
    getParentRoute: () => PathlessLayoutNestedLayoutRoute,
  } as any)

const PathlessLayoutNestedLayoutRouteARoute =
  PathlessLayoutNestedLayoutRouteAImport.update({
    id: '/route-a',
    path: '/route-a',
    getParentRoute: () => PathlessLayoutNestedLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRoute
    }
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_pathlessLayout/_nested-layout': {
      id: '/_pathlessLayout/_nested-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessLayoutNestedLayoutImport
      parentRoute: typeof PathlessLayoutImport
    }
    '/comunicados/$comunicadoId': {
      id: '/comunicados/$comunicadoId'
      path: '/comunicados/$comunicadoId'
      fullPath: '/comunicados/$comunicadoId'
      preLoaderRoute: typeof ComunicadosComunicadoIdImport
      parentRoute: typeof rootRoute
    }
    '/noticias/$noticiaSlug': {
      id: '/noticias/$noticiaSlug'
      path: '/noticias/$noticiaSlug'
      fullPath: '/noticias/$noticiaSlug'
      preLoaderRoute: typeof NoticiasNoticiaSlugImport
      parentRoute: typeof rootRoute
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdImport
      parentRoute: typeof PostsRouteImport
    }
    '/comunicados/': {
      id: '/comunicados/'
      path: '/comunicados'
      fullPath: '/comunicados'
      preLoaderRoute: typeof ComunicadosIndexImport
      parentRoute: typeof rootRoute
    }
    '/noticias/': {
      id: '/noticias/'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasIndexImport
      parentRoute: typeof rootRoute
    }
    '/posts/': {
      id: '/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexImport
      parentRoute: typeof PostsRouteImport
    }
    '/rating/': {
      id: '/rating/'
      path: '/rating'
      fullPath: '/rating'
      preLoaderRoute: typeof RatingIndexImport
      parentRoute: typeof rootRoute
    }
    '/_pathlessLayout/_nested-layout/route-a': {
      id: '/_pathlessLayout/_nested-layout/route-a'
      path: '/route-a'
      fullPath: '/route-a'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteAImport
      parentRoute: typeof PathlessLayoutNestedLayoutImport
    }
    '/_pathlessLayout/_nested-layout/route-b': {
      id: '/_pathlessLayout/_nested-layout/route-b'
      path: '/route-b'
      fullPath: '/route-b'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteBImport
      parentRoute: typeof PathlessLayoutNestedLayoutImport
    }
  }
}

// Create and export the route tree

interface PostsRouteRouteChildren {
  PostsPostIdRoute: typeof PostsPostIdRoute
  PostsIndexRoute: typeof PostsIndexRoute
}

const PostsRouteRouteChildren: PostsRouteRouteChildren = {
  PostsPostIdRoute: PostsPostIdRoute,
  PostsIndexRoute: PostsIndexRoute,
}

const PostsRouteRouteWithChildren = PostsRouteRoute._addFileChildren(
  PostsRouteRouteChildren,
)

interface PathlessLayoutNestedLayoutRouteChildren {
  PathlessLayoutNestedLayoutRouteARoute: typeof PathlessLayoutNestedLayoutRouteARoute
  PathlessLayoutNestedLayoutRouteBRoute: typeof PathlessLayoutNestedLayoutRouteBRoute
}

const PathlessLayoutNestedLayoutRouteChildren: PathlessLayoutNestedLayoutRouteChildren =
  {
    PathlessLayoutNestedLayoutRouteARoute:
      PathlessLayoutNestedLayoutRouteARoute,
    PathlessLayoutNestedLayoutRouteBRoute:
      PathlessLayoutNestedLayoutRouteBRoute,
  }

const PathlessLayoutNestedLayoutRouteWithChildren =
  PathlessLayoutNestedLayoutRoute._addFileChildren(
    PathlessLayoutNestedLayoutRouteChildren,
  )

interface PathlessLayoutRouteChildren {
  PathlessLayoutNestedLayoutRoute: typeof PathlessLayoutNestedLayoutRouteWithChildren
}

const PathlessLayoutRouteChildren: PathlessLayoutRouteChildren = {
  PathlessLayoutNestedLayoutRoute: PathlessLayoutNestedLayoutRouteWithChildren,
}

const PathlessLayoutRouteWithChildren = PathlessLayoutRoute._addFileChildren(
  PathlessLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/posts': typeof PostsRouteRouteWithChildren
  '': typeof PathlessLayoutNestedLayoutRouteWithChildren
  '/comunicados/$comunicadoId': typeof ComunicadosComunicadoIdRoute
  '/noticias/$noticiaSlug': typeof NoticiasNoticiaSlugRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/comunicados': typeof ComunicadosIndexRoute
  '/noticias': typeof NoticiasIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/rating': typeof RatingIndexRoute
  '/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof PathlessLayoutNestedLayoutRouteWithChildren
  '/comunicados/$comunicadoId': typeof ComunicadosComunicadoIdRoute
  '/noticias/$noticiaSlug': typeof NoticiasNoticiaSlugRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/comunicados': typeof ComunicadosIndexRoute
  '/noticias': typeof NoticiasIndexRoute
  '/posts': typeof PostsIndexRoute
  '/rating': typeof RatingIndexRoute
  '/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/posts': typeof PostsRouteRouteWithChildren
  '/_pathlessLayout': typeof PathlessLayoutRouteWithChildren
  '/_pathlessLayout/_nested-layout': typeof PathlessLayoutNestedLayoutRouteWithChildren
  '/comunicados/$comunicadoId': typeof ComunicadosComunicadoIdRoute
  '/noticias/$noticiaSlug': typeof NoticiasNoticiaSlugRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/comunicados/': typeof ComunicadosIndexRoute
  '/noticias/': typeof NoticiasIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/rating/': typeof RatingIndexRoute
  '/_pathlessLayout/_nested-layout/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/_pathlessLayout/_nested-layout/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/posts'
    | ''
    | '/comunicados/$comunicadoId'
    | '/noticias/$noticiaSlug'
    | '/posts/$postId'
    | '/comunicados'
    | '/noticias'
    | '/posts/'
    | '/rating'
    | '/route-a'
    | '/route-b'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/comunicados/$comunicadoId'
    | '/noticias/$noticiaSlug'
    | '/posts/$postId'
    | '/comunicados'
    | '/noticias'
    | '/posts'
    | '/rating'
    | '/route-a'
    | '/route-b'
  id:
    | '__root__'
    | '/'
    | '/posts'
    | '/_pathlessLayout'
    | '/_pathlessLayout/_nested-layout'
    | '/comunicados/$comunicadoId'
    | '/noticias/$noticiaSlug'
    | '/posts/$postId'
    | '/comunicados/'
    | '/noticias/'
    | '/posts/'
    | '/rating/'
    | '/_pathlessLayout/_nested-layout/route-a'
    | '/_pathlessLayout/_nested-layout/route-b'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PostsRouteRoute: typeof PostsRouteRouteWithChildren
  PathlessLayoutRoute: typeof PathlessLayoutRouteWithChildren
  ComunicadosComunicadoIdRoute: typeof ComunicadosComunicadoIdRoute
  NoticiasNoticiaSlugRoute: typeof NoticiasNoticiaSlugRoute
  ComunicadosIndexRoute: typeof ComunicadosIndexRoute
  NoticiasIndexRoute: typeof NoticiasIndexRoute
  RatingIndexRoute: typeof RatingIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PostsRouteRoute: PostsRouteRouteWithChildren,
  PathlessLayoutRoute: PathlessLayoutRouteWithChildren,
  ComunicadosComunicadoIdRoute: ComunicadosComunicadoIdRoute,
  NoticiasNoticiaSlugRoute: NoticiasNoticiaSlugRoute,
  ComunicadosIndexRoute: ComunicadosIndexRoute,
  NoticiasIndexRoute: NoticiasIndexRoute,
  RatingIndexRoute: RatingIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/posts",
        "/_pathlessLayout",
        "/comunicados/$comunicadoId",
        "/noticias/$noticiaSlug",
        "/comunicados/",
        "/noticias/",
        "/rating/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/posts": {
      "filePath": "posts.route.tsx",
      "children": [
        "/posts/$postId",
        "/posts/"
      ]
    },
    "/_pathlessLayout": {
      "filePath": "_pathlessLayout.tsx",
      "children": [
        "/_pathlessLayout/_nested-layout"
      ]
    },
    "/_pathlessLayout/_nested-layout": {
      "filePath": "_pathlessLayout/_nested-layout.tsx",
      "parent": "/_pathlessLayout",
      "children": [
        "/_pathlessLayout/_nested-layout/route-a",
        "/_pathlessLayout/_nested-layout/route-b"
      ]
    },
    "/comunicados/$comunicadoId": {
      "filePath": "comunicados/$comunicadoId.tsx"
    },
    "/noticias/$noticiaSlug": {
      "filePath": "noticias/$noticiaSlug.tsx"
    },
    "/posts/$postId": {
      "filePath": "posts.$postId.tsx",
      "parent": "/posts"
    },
    "/comunicados/": {
      "filePath": "comunicados/index.tsx"
    },
    "/noticias/": {
      "filePath": "noticias/index.tsx"
    },
    "/posts/": {
      "filePath": "posts.index.tsx",
      "parent": "/posts"
    },
    "/rating/": {
      "filePath": "rating/index.tsx"
    },
    "/_pathlessLayout/_nested-layout/route-a": {
      "filePath": "_pathlessLayout/_nested-layout/route-a.tsx",
      "parent": "/_pathlessLayout/_nested-layout"
    },
    "/_pathlessLayout/_nested-layout/route-b": {
      "filePath": "_pathlessLayout/_nested-layout/route-b.tsx",
      "parent": "/_pathlessLayout/_nested-layout"
    }
  }
}
ROUTE_MANIFEST_END */
