/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard/route'
import { Route as ParamsRouteImport } from './routes/_params/route'
import { Route as DefaultRouteImport } from './routes/_default/route'
import { Route as DefaultIndexImport } from './routes/_default/index'
import { Route as DashboardSignupImport } from './routes/dashboard/signup'
import { Route as DashboardLogoutImport } from './routes/dashboard/logout'
import { Route as DashboardLoginImport } from './routes/dashboard/login'
import { Route as DefaultTituladosIndexImport } from './routes/_default/titulados/index'
import { Route as DefaultTestIndexImport } from './routes/_default/test/index'
import { Route as DefaultSobreIndexImport } from './routes/_default/sobre/index'
import { Route as DefaultRatingsIndexImport } from './routes/_default/ratings/index'
import { Route as DefaultNoticiasIndexImport } from './routes/_default/noticias/index'
import { Route as DefaultMembrosIndexImport } from './routes/_default/membros/index'
import { Route as DefaultComunicadosIndexImport } from './routes/_default/comunicados/index'
import { Route as DefaultCircuitosIndexImport } from './routes/_default/circuitos/index'
import { Route as DefaultCampeoesIndexImport } from './routes/_default/campeoes/index'
import { Route as ParamsNoticiasNoticiaSlugImport } from './routes/_params/noticias/$noticiaSlug'
import { Route as ParamsJogadoresJogadorIdImport } from './routes/_params/jogadores/$jogadorId'

// Create/Update Routes

const DashboardRouteRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const ParamsRouteRoute = ParamsRouteImport.update({
  id: '/_params',
  getParentRoute: () => rootRoute,
} as any)

const DefaultRouteRoute = DefaultRouteImport.update({
  id: '/_default',
  getParentRoute: () => rootRoute,
} as any)

const DefaultIndexRoute = DefaultIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DefaultRouteRoute,
} as any)

const DashboardSignupRoute = DashboardSignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardLogoutRoute = DashboardLogoutImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardLoginRoute = DashboardLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DefaultTituladosIndexRoute = DefaultTituladosIndexImport.update({
  id: '/titulados/',
  path: '/titulados/',
  getParentRoute: () => DefaultRouteRoute,
} as any)

const DefaultTestIndexRoute = DefaultTestIndexImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => DefaultRouteRoute,
} as any)

const DefaultSobreIndexRoute = DefaultSobreIndexImport.update({
  id: '/sobre/',
  path: '/sobre/',
  getParentRoute: () => DefaultRouteRoute,
} as any)

const DefaultRatingsIndexRoute = DefaultRatingsIndexImport.update({
  id: '/ratings/',
  path: '/ratings/',
  getParentRoute: () => DefaultRouteRoute,
} as any)

const DefaultNoticiasIndexRoute = DefaultNoticiasIndexImport.update({
  id: '/noticias/',
  path: '/noticias/',
  getParentRoute: () => DefaultRouteRoute,
} as any)

const DefaultMembrosIndexRoute = DefaultMembrosIndexImport.update({
  id: '/membros/',
  path: '/membros/',
  getParentRoute: () => DefaultRouteRoute,
} as any)

const DefaultComunicadosIndexRoute = DefaultComunicadosIndexImport.update({
  id: '/comunicados/',
  path: '/comunicados/',
  getParentRoute: () => DefaultRouteRoute,
} as any)

const DefaultCircuitosIndexRoute = DefaultCircuitosIndexImport.update({
  id: '/circuitos/',
  path: '/circuitos/',
  getParentRoute: () => DefaultRouteRoute,
} as any)

const DefaultCampeoesIndexRoute = DefaultCampeoesIndexImport.update({
  id: '/campeoes/',
  path: '/campeoes/',
  getParentRoute: () => DefaultRouteRoute,
} as any)

const ParamsNoticiasNoticiaSlugRoute = ParamsNoticiasNoticiaSlugImport.update({
  id: '/noticias/$noticiaSlug',
  path: '/noticias/$noticiaSlug',
  getParentRoute: () => ParamsRouteRoute,
} as any)

const ParamsJogadoresJogadorIdRoute = ParamsJogadoresJogadorIdImport.update({
  id: '/jogadores/$jogadorId',
  path: '/jogadores/$jogadorId',
  getParentRoute: () => ParamsRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_default': {
      id: '/_default'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DefaultRouteImport
      parentRoute: typeof rootRoute
    }
    '/_params': {
      id: '/_params'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ParamsRouteImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/login': {
      id: '/dashboard/login'
      path: '/login'
      fullPath: '/dashboard/login'
      preLoaderRoute: typeof DashboardLoginImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/logout': {
      id: '/dashboard/logout'
      path: '/logout'
      fullPath: '/dashboard/logout'
      preLoaderRoute: typeof DashboardLogoutImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/signup': {
      id: '/dashboard/signup'
      path: '/signup'
      fullPath: '/dashboard/signup'
      preLoaderRoute: typeof DashboardSignupImport
      parentRoute: typeof DashboardRouteImport
    }
    '/_default/': {
      id: '/_default/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DefaultIndexImport
      parentRoute: typeof DefaultRouteImport
    }
    '/_params/jogadores/$jogadorId': {
      id: '/_params/jogadores/$jogadorId'
      path: '/jogadores/$jogadorId'
      fullPath: '/jogadores/$jogadorId'
      preLoaderRoute: typeof ParamsJogadoresJogadorIdImport
      parentRoute: typeof ParamsRouteImport
    }
    '/_params/noticias/$noticiaSlug': {
      id: '/_params/noticias/$noticiaSlug'
      path: '/noticias/$noticiaSlug'
      fullPath: '/noticias/$noticiaSlug'
      preLoaderRoute: typeof ParamsNoticiasNoticiaSlugImport
      parentRoute: typeof ParamsRouteImport
    }
    '/_default/campeoes/': {
      id: '/_default/campeoes/'
      path: '/campeoes'
      fullPath: '/campeoes'
      preLoaderRoute: typeof DefaultCampeoesIndexImport
      parentRoute: typeof DefaultRouteImport
    }
    '/_default/circuitos/': {
      id: '/_default/circuitos/'
      path: '/circuitos'
      fullPath: '/circuitos'
      preLoaderRoute: typeof DefaultCircuitosIndexImport
      parentRoute: typeof DefaultRouteImport
    }
    '/_default/comunicados/': {
      id: '/_default/comunicados/'
      path: '/comunicados'
      fullPath: '/comunicados'
      preLoaderRoute: typeof DefaultComunicadosIndexImport
      parentRoute: typeof DefaultRouteImport
    }
    '/_default/membros/': {
      id: '/_default/membros/'
      path: '/membros'
      fullPath: '/membros'
      preLoaderRoute: typeof DefaultMembrosIndexImport
      parentRoute: typeof DefaultRouteImport
    }
    '/_default/noticias/': {
      id: '/_default/noticias/'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof DefaultNoticiasIndexImport
      parentRoute: typeof DefaultRouteImport
    }
    '/_default/ratings/': {
      id: '/_default/ratings/'
      path: '/ratings'
      fullPath: '/ratings'
      preLoaderRoute: typeof DefaultRatingsIndexImport
      parentRoute: typeof DefaultRouteImport
    }
    '/_default/sobre/': {
      id: '/_default/sobre/'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof DefaultSobreIndexImport
      parentRoute: typeof DefaultRouteImport
    }
    '/_default/test/': {
      id: '/_default/test/'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof DefaultTestIndexImport
      parentRoute: typeof DefaultRouteImport
    }
    '/_default/titulados/': {
      id: '/_default/titulados/'
      path: '/titulados'
      fullPath: '/titulados'
      preLoaderRoute: typeof DefaultTituladosIndexImport
      parentRoute: typeof DefaultRouteImport
    }
  }
}

// Create and export the route tree

interface DefaultRouteRouteChildren {
  DefaultIndexRoute: typeof DefaultIndexRoute
  DefaultCampeoesIndexRoute: typeof DefaultCampeoesIndexRoute
  DefaultCircuitosIndexRoute: typeof DefaultCircuitosIndexRoute
  DefaultComunicadosIndexRoute: typeof DefaultComunicadosIndexRoute
  DefaultMembrosIndexRoute: typeof DefaultMembrosIndexRoute
  DefaultNoticiasIndexRoute: typeof DefaultNoticiasIndexRoute
  DefaultRatingsIndexRoute: typeof DefaultRatingsIndexRoute
  DefaultSobreIndexRoute: typeof DefaultSobreIndexRoute
  DefaultTestIndexRoute: typeof DefaultTestIndexRoute
  DefaultTituladosIndexRoute: typeof DefaultTituladosIndexRoute
}

const DefaultRouteRouteChildren: DefaultRouteRouteChildren = {
  DefaultIndexRoute: DefaultIndexRoute,
  DefaultCampeoesIndexRoute: DefaultCampeoesIndexRoute,
  DefaultCircuitosIndexRoute: DefaultCircuitosIndexRoute,
  DefaultComunicadosIndexRoute: DefaultComunicadosIndexRoute,
  DefaultMembrosIndexRoute: DefaultMembrosIndexRoute,
  DefaultNoticiasIndexRoute: DefaultNoticiasIndexRoute,
  DefaultRatingsIndexRoute: DefaultRatingsIndexRoute,
  DefaultSobreIndexRoute: DefaultSobreIndexRoute,
  DefaultTestIndexRoute: DefaultTestIndexRoute,
  DefaultTituladosIndexRoute: DefaultTituladosIndexRoute,
}

const DefaultRouteRouteWithChildren = DefaultRouteRoute._addFileChildren(
  DefaultRouteRouteChildren,
)

interface ParamsRouteRouteChildren {
  ParamsJogadoresJogadorIdRoute: typeof ParamsJogadoresJogadorIdRoute
  ParamsNoticiasNoticiaSlugRoute: typeof ParamsNoticiasNoticiaSlugRoute
}

const ParamsRouteRouteChildren: ParamsRouteRouteChildren = {
  ParamsJogadoresJogadorIdRoute: ParamsJogadoresJogadorIdRoute,
  ParamsNoticiasNoticiaSlugRoute: ParamsNoticiasNoticiaSlugRoute,
}

const ParamsRouteRouteWithChildren = ParamsRouteRoute._addFileChildren(
  ParamsRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardLoginRoute: typeof DashboardLoginRoute
  DashboardLogoutRoute: typeof DashboardLogoutRoute
  DashboardSignupRoute: typeof DashboardSignupRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardLoginRoute: DashboardLoginRoute,
  DashboardLogoutRoute: DashboardLogoutRoute,
  DashboardSignupRoute: DashboardSignupRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof ParamsRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/login': typeof DashboardLoginRoute
  '/dashboard/logout': typeof DashboardLogoutRoute
  '/dashboard/signup': typeof DashboardSignupRoute
  '/': typeof DefaultIndexRoute
  '/jogadores/$jogadorId': typeof ParamsJogadoresJogadorIdRoute
  '/noticias/$noticiaSlug': typeof ParamsNoticiasNoticiaSlugRoute
  '/campeoes': typeof DefaultCampeoesIndexRoute
  '/circuitos': typeof DefaultCircuitosIndexRoute
  '/comunicados': typeof DefaultComunicadosIndexRoute
  '/membros': typeof DefaultMembrosIndexRoute
  '/noticias': typeof DefaultNoticiasIndexRoute
  '/ratings': typeof DefaultRatingsIndexRoute
  '/sobre': typeof DefaultSobreIndexRoute
  '/test': typeof DefaultTestIndexRoute
  '/titulados': typeof DefaultTituladosIndexRoute
}

export interface FileRoutesByTo {
  '': typeof ParamsRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/login': typeof DashboardLoginRoute
  '/dashboard/logout': typeof DashboardLogoutRoute
  '/dashboard/signup': typeof DashboardSignupRoute
  '/': typeof DefaultIndexRoute
  '/jogadores/$jogadorId': typeof ParamsJogadoresJogadorIdRoute
  '/noticias/$noticiaSlug': typeof ParamsNoticiasNoticiaSlugRoute
  '/campeoes': typeof DefaultCampeoesIndexRoute
  '/circuitos': typeof DefaultCircuitosIndexRoute
  '/comunicados': typeof DefaultComunicadosIndexRoute
  '/membros': typeof DefaultMembrosIndexRoute
  '/noticias': typeof DefaultNoticiasIndexRoute
  '/ratings': typeof DefaultRatingsIndexRoute
  '/sobre': typeof DefaultSobreIndexRoute
  '/test': typeof DefaultTestIndexRoute
  '/titulados': typeof DefaultTituladosIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_default': typeof DefaultRouteRouteWithChildren
  '/_params': typeof ParamsRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/login': typeof DashboardLoginRoute
  '/dashboard/logout': typeof DashboardLogoutRoute
  '/dashboard/signup': typeof DashboardSignupRoute
  '/_default/': typeof DefaultIndexRoute
  '/_params/jogadores/$jogadorId': typeof ParamsJogadoresJogadorIdRoute
  '/_params/noticias/$noticiaSlug': typeof ParamsNoticiasNoticiaSlugRoute
  '/_default/campeoes/': typeof DefaultCampeoesIndexRoute
  '/_default/circuitos/': typeof DefaultCircuitosIndexRoute
  '/_default/comunicados/': typeof DefaultComunicadosIndexRoute
  '/_default/membros/': typeof DefaultMembrosIndexRoute
  '/_default/noticias/': typeof DefaultNoticiasIndexRoute
  '/_default/ratings/': typeof DefaultRatingsIndexRoute
  '/_default/sobre/': typeof DefaultSobreIndexRoute
  '/_default/test/': typeof DefaultTestIndexRoute
  '/_default/titulados/': typeof DefaultTituladosIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/dashboard'
    | '/dashboard/login'
    | '/dashboard/logout'
    | '/dashboard/signup'
    | '/'
    | '/jogadores/$jogadorId'
    | '/noticias/$noticiaSlug'
    | '/campeoes'
    | '/circuitos'
    | '/comunicados'
    | '/membros'
    | '/noticias'
    | '/ratings'
    | '/sobre'
    | '/test'
    | '/titulados'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/dashboard'
    | '/dashboard/login'
    | '/dashboard/logout'
    | '/dashboard/signup'
    | '/'
    | '/jogadores/$jogadorId'
    | '/noticias/$noticiaSlug'
    | '/campeoes'
    | '/circuitos'
    | '/comunicados'
    | '/membros'
    | '/noticias'
    | '/ratings'
    | '/sobre'
    | '/test'
    | '/titulados'
  id:
    | '__root__'
    | '/_default'
    | '/_params'
    | '/dashboard'
    | '/dashboard/login'
    | '/dashboard/logout'
    | '/dashboard/signup'
    | '/_default/'
    | '/_params/jogadores/$jogadorId'
    | '/_params/noticias/$noticiaSlug'
    | '/_default/campeoes/'
    | '/_default/circuitos/'
    | '/_default/comunicados/'
    | '/_default/membros/'
    | '/_default/noticias/'
    | '/_default/ratings/'
    | '/_default/sobre/'
    | '/_default/test/'
    | '/_default/titulados/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  DefaultRouteRoute: typeof DefaultRouteRouteWithChildren
  ParamsRouteRoute: typeof ParamsRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  DefaultRouteRoute: DefaultRouteRouteWithChildren,
  ParamsRouteRoute: ParamsRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_default",
        "/_params",
        "/dashboard"
      ]
    },
    "/_default": {
      "filePath": "_default/route.tsx",
      "children": [
        "/_default/",
        "/_default/campeoes/",
        "/_default/circuitos/",
        "/_default/comunicados/",
        "/_default/membros/",
        "/_default/noticias/",
        "/_default/ratings/",
        "/_default/sobre/",
        "/_default/test/",
        "/_default/titulados/"
      ]
    },
    "/_params": {
      "filePath": "_params/route.tsx",
      "children": [
        "/_params/jogadores/$jogadorId",
        "/_params/noticias/$noticiaSlug"
      ]
    },
    "/dashboard": {
      "filePath": "dashboard/route.tsx",
      "children": [
        "/dashboard/login",
        "/dashboard/logout",
        "/dashboard/signup"
      ]
    },
    "/dashboard/login": {
      "filePath": "dashboard/login.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/logout": {
      "filePath": "dashboard/logout.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/signup": {
      "filePath": "dashboard/signup.tsx",
      "parent": "/dashboard"
    },
    "/_default/": {
      "filePath": "_default/index.tsx",
      "parent": "/_default"
    },
    "/_params/jogadores/$jogadorId": {
      "filePath": "_params/jogadores/$jogadorId.tsx",
      "parent": "/_params"
    },
    "/_params/noticias/$noticiaSlug": {
      "filePath": "_params/noticias/$noticiaSlug.tsx",
      "parent": "/_params"
    },
    "/_default/campeoes/": {
      "filePath": "_default/campeoes/index.tsx",
      "parent": "/_default"
    },
    "/_default/circuitos/": {
      "filePath": "_default/circuitos/index.tsx",
      "parent": "/_default"
    },
    "/_default/comunicados/": {
      "filePath": "_default/comunicados/index.tsx",
      "parent": "/_default"
    },
    "/_default/membros/": {
      "filePath": "_default/membros/index.tsx",
      "parent": "/_default"
    },
    "/_default/noticias/": {
      "filePath": "_default/noticias/index.tsx",
      "parent": "/_default"
    },
    "/_default/ratings/": {
      "filePath": "_default/ratings/index.tsx",
      "parent": "/_default"
    },
    "/_default/sobre/": {
      "filePath": "_default/sobre/index.tsx",
      "parent": "/_default"
    },
    "/_default/test/": {
      "filePath": "_default/test/index.tsx",
      "parent": "/_default"
    },
    "/_default/titulados/": {
      "filePath": "_default/titulados/index.tsx",
      "parent": "/_default"
    }
  }
}
ROUTE_MANIFEST_END */
